# filename: templates/typescript-basic-webserver/manifests/deployment.yaml
# Kubernetes deployment configuration for the web application
# Template variables:
# terchris - Will be replaced with the GitHub username from the repository URL
# urb-dev-designsystemet-basic-react-app - Will be replaced with the actual repository name
#
# This file is automatically configured during project initialization

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "urb-dev-designsystemet-basic-react-app-deployment"
  labels:
    app: "urb-dev-designsystemet-basic-react-app"
    owner: "terchris"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "urb-dev-designsystemet-basic-react-app"
  template:
    metadata:
      labels:
        app: "urb-dev-designsystemet-basic-react-app"
    spec:
      containers:
        - name: "urb-dev-designsystemet-basic-react-app"
          image: ghcr.io/terchris/urb-dev-designsystemet-basic-react-app:f5feeff-20250422144732
          ports:
            - containerPort: 3000
          # minimal resources as this is just a test            
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: "urb-dev-designsystemet-basic-react-app-service"
spec:
  selector:
    app: "urb-dev-designsystemet-basic-react-app"
  ports:
    - port: 80
      targetPort: 3000